<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Instagram Clone</title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/assets/css/jumbotron.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.ui.widget.js"></script>
    <script src="/assets/js/fileUpload.js"></script>
    
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'index')); ?>">Instagram Clone</a>
            <ul class="nav navbar-nav">
                 <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'friends')); ?>">Find Friends</a></li>
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
                   <ul class="dropdown-menu">
                     <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'photos')); ?>">My Photos</a></li>
                     <li><a href="<?php echo $this->url(array('controller' => 'profile', 'action' => 'settings')); ?>">Account Settings</a></li>
                   </ul>
                 </li>
                 <li><a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout')); ?>">Logout</a></li>
             </ul>
        </div>
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <h1>Welcome, <?php echo ucwords($this->user->first_name . ' ' . $this->user->last_name); ?>!</h1>
      </div>
    </div>

    <div class="container">
        <?php echo $this->layout()->content; ?>
      <hr>

      <footer>
        <p>&copy; Eric Ruvio 2013</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>
