<h3>Add/Remove Friends</h3><hr/>

<form role="form" method="POST" action="<?php echo $this->url(array('controller' => 'profile', 'action' => 'friends')); ?>">

    <?php foreach($this->users as $user) : ?>

      <div class="checkbox">
        <label>
          <input type="checkbox" name="friends[]" value="<?php echo (int)$user->user_id; ?>" <?php if($user->is_friend) : ?>checked<?php endif; ?>> <?php echo ucwords($user->first_name . ' ' . $user->last_name); ?>
        </label>
      </div>

    <?php endforeach; ?>
    
    <button type="submit" class="btn btn-default">Submit</button>
</form>
    