<form role="form" action="<?php echo $this->url(array('controller' => 'profile', 'action' => 'settings')); ?>" method="POST">
  <div class="form-group">
    <label>Email address</label>
    <input type="text" name="email" class="form-control" value="<?php echo $this->user->email; ?>" placeholder="Enter email">
  </div>
    
      <div class="form-group">
    <label>Password</label>
    <input type="password" name="password" class="form-control" placeholder="Enter password">
  </div>
    
      <div class="form-group">
    <label>First Name</label>
    <input type="text" name="first_name" class="form-control" value="<?php echo $this->user->first_name; ?>" placeholder="Enter First Name">
  </div>
    
        <div class="form-group">
    <label>First Name</label>
    <input type="text" name="last_name" class="form-control" value="<?php echo $this->user->last_name; ?>" placeholder="Enter Last Name">
  </div>
  
    
  <button type="submit" class="btn btn-default">Submit</button>
</form>